### ISSUE TITLE
Refactor website tests [ongoing]

### ISSUE THREAD

**Issue by merrielle** [Breakthrough-Energy/PostREISE#139]
This task is to keep track of all the tests that need to be added or updated in CENACS in an effort to burn down technical debt. I don't expect this will be complete by the end of the WTT90s milestone but instead it should be an ongoing process until we are completely caught up.

## Kamilah
- [ ] collapsible text
- [ ] dashboard test (just check that existing tests pass)
- [x] dashboard slice - mostly done, needs update filter function
- [ ] all graphs that have "format data"
  - [ ] focus on the format data functions since they're isolated
  - [ ] investigate an apollo testing guide to see if it's easy to test the useQuery part
  - [ ] generation pie
  - [ ] generation bar
  - [ ] generation stacked line
  - [ ] curtailment line
- [ ] util
  - [ ] sortByTimestamp
  - [ ] sortByResourceType
  - [x] increaseUnitSize
- [ ] docker - investigate and see if testing is worth the time investment

## Merrielle
- [ ] header
- [ ] select
- [ ] graphColumn
- [ ] scenario toolbar
- [ ] scrollytelling
- [ ] bokehGraph (waiting on merge from S Dan: https://github.com/Breakthrough-Energy/CENACS/pull/80)
- [ ] graphWrapper
