### ISSUE TITLE
Consolidate Data Access Code in PowerSimData

### ISSUE THREAD

**Issue by ahurli** [Breakthrough-Energy/PostREISE#321]
# :rocket:

- [ ] Is your feature request essential for your project?

### Describe the workflow you want to enable
Currently, code to read/write data in `PowerSimData` is implemented outside of the new pyfilesystem changes (which handle moving/deleting existing files in `data_access`). The proposed change is to handle the read/write in a consolidated place (i.e. either `input_data` or `data_access`) so that it can then be switched over to use the same pyfilesystem. Specifically, creating file paths and file-type objects should be handled in a single location.

### Describe your proposed implementation
* - [ ] Define expected read/write functionality outside of powersimdata workflow (e.g. export_case_mat in powersimdata/input/export_data was refactored out so that ext. collaborators could manually save a case.mat to examine/test without starting a simulation). How and where do we need to expose these functions, both for now and in the future?
* - [ ] Decide design for where the new file objects will be created and what their lifecycle looks like
* - [ ] Update direct-to-local read/writes of data (i.e. pandas, pickle, or scipy.io)
    - [ ] input/change_table.py: pickle dump
    - [ ] input/export_data.py: savemat, pandas csv
    - [ ] data_access/csv_store.py: pandas csv
    - [ ] output/output_data.py: pandas pickle
* - [ ] Consolidate path building from anywhere outside of data access/input_data (in addition to above)
    - [ ] create.py
    - [ ] execute.py
    - [ ] analyze.py
    - [ ] move.py
    - [ ] delete.py
